
version: "3.8"
networks:
  ab_testing_framework_network:
  default:
    name: ab_testing_framework_network
services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - ab-testing-framework-postgres:/var/lib/postgresql/data
    networks:
      - ab_testing_framework_network

  ab-testing-framework-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5000:5000"
    networks:
      - ab_testing_framework_network
        
volumes:
  ab-testing-framework-postgres: