
version: "3.8"
networks:
  community_feedback_network:
  default:
    name: community_feedback_network
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - community-feedback-postgres:/var/lib/postgresql/data
    networks:
      - community_feedback_network

  community-feedback-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5000:5000"
    networks:
      - community_feedback_network
        
volumes:
  community-feedback-postgres: